### ISSUE TITLE
[Draft] Ruby 3.2 support 

### ISSUE THREAD

**Issue by CAMOBAP** [relaton/relaton#111]
https://github.com/metanorma/metanorma-cli/actions/runs/4101141447/jobs/7073600661#step:7:30

```
Fatal Error: Refinement#include has been removed
bundler: failed to load command: metanorma (/Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/bin/metanorma)
/Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/rdf-n3-3.1.2/lib/rdf/n3/refinements.rb:176:in `include': Refinement#include has been removed (TypeError)

    include ::RDF::Term
            ^^^^^^^^^^^
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/rdf-n3-3.1.2/lib/rdf/n3/refinements.rb:176:in `block in <module:Refinements>'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/rdf-n3-3.1.2/lib/rdf/n3/refinements.rb:174:in `refine'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/rdf-n3-3.1.2/lib/rdf/n3/refinements.rb:174:in `<module:Refinements>'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/rdf-n3-3.1.2/lib/rdf/n3/refinements.rb:2:in `<top (required)>'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/rdf-n3-3.1.2/lib/rdf/n3.rb:26:in `require'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/rdf-n3-3.1.2/lib/rdf/n3.rb:26:in `<module:N3>'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/rdf-n3-3.1.2/lib/rdf/n3.rb:21:in `<module:RDF>'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/rdf-n3-3.1.2/lib/rdf/n3.rb:3:in `<top (required)>'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/linkeddata-3.1.6/lib/linkeddata.rb:26:in `require'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/linkeddata-3.1.6/lib/linkeddata.rb:26:in `<module:LinkedData>'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/linkeddata-3.1.6/lib/linkeddata.rb:1:in `<top (required)>'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/relaton-w3c-1.14.0/lib/relaton_w3c/data_fetcher.rb:2:in `require'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/relaton-w3c-1.14.0/lib/relaton_w3c/data_fetcher.rb:2:in `<top (required)>'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/relaton-w3c-1.14.0/lib/relaton_w3c.rb:8:in `require'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/relaton-w3c-1.14.0/lib/relaton_w3c.rb:8:in `<top (required)>'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/relaton-1.14.2/lib/relaton/registry.rb:28:in `require'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/relaton-1.14.2/lib/relaton/registry.rb:28:in `block in register_gems'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/relaton-1.14.2/lib/relaton/registry.rb:27:in `each'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/relaton-1.14.2/lib/relaton/registry.rb:27:in `register_gems'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/relaton-1.14.2/lib/relaton/registry.rb:21:in `initialize'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/3.2.0/singleton.rb:127:in `new'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/3.2.0/singleton.rb:127:in `block in instance'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/3.2.0/singleton.rb:125:in `synchronize'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/3.2.0/singleton.rb:125:in `instance'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/relaton-1.14.2/lib/relaton/db.rb:6:in `initialize'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/relaton-1.14.2/lib/relaton/db.rb:530:in `new'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/relaton-1.14.2/lib/relaton/db.rb:530:in `init_bib_caches'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/metanorma-standoc-2.3.7/lib/metanorma/standoc/ref_sect.rb:166:in `init_bib_caches'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/metanorma-standoc-2.3.7/lib/metanorma/standoc/base.rb:119:in `init_biblio'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/metanorma-standoc-2.3.7/lib/metanorma/standoc/base.rb:40:in `init'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/metanorma-iso-2.3.3/lib/metanorma/iso/base.rb:54:in `init'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/metanorma-standoc-2.3.7/lib/metanorma/standoc/base.rb:140:in `document1'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/metanorma-standoc-2.3.7/lib/metanorma/standoc/base.rb:130:in `document'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/metanorma-standoc-2.3.7/lib/metanorma/standoc/utils.rb:13:in `convert'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/asciidoctor-2.0.18/lib/asciidoctor/document.rb:956:in `convert'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/asciidoctor-2.0.18/lib/asciidoctor/convert.rb:120:in `convert'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/metanorma-1.5.5/lib/metanorma/input/asciidoc.rb:18:in `process'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/metanorma-1.5.5/lib/metanorma/processor.rb:21:in `input_to_isodoc'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/metanorma-1.5.5/lib/metanorma/compile.rb:59:in `process_input_adoc'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/metanorma-1.5.5/lib/metanorma/compile.rb:42:in `process_input'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/metanorma-1.5.5/lib/metanorma/compile.rb:33:in `compile'
	from /Users/runner/work/metanorma-cli/metanorma-cli/lib/metanorma/cli/compiler.rb:45:in `compile_file'
	from /Users/runner/work/metanorma-cli/metanorma-cli/lib/metanorma/cli/compiler.rb:30:in `compile'
	from /Users/runner/work/metanorma-cli/metanorma-cli/lib/metanorma/cli/compiler.rb:35:in `compile'
	from /Users/runner/work/metanorma-cli/metanorma-cli/lib/metanorma/cli/site_generator.rb:89:in `compile'
	from /Users/runner/work/metanorma-cli/metanorma-cli/lib/metanorma/cli/site_generator.rb:[29](https://github.com/metanorma/metanorma-cli/actions/runs/4101141447/jobs/7073600661#step:7:31):in `block in generate'
	from /Users/runner/work/metanorma-cli/metanorma-cli/lib/metanorma/cli/site_generator.rb:29:in `each'
	from /Users/runner/work/metanorma-cli/metanorma-cli/lib/metanorma/cli/site_generator.rb:29:in `generate'
	from /Users/runner/work/metanorma-cli/metanorma-cli/lib/metanorma/cli/site_generator.rb:24:in `generate'
	from /Users/runner/work/metanorma-cli/metanorma-cli/lib/metanorma/cli/commands/site.rb:[31](https://github.com/metanorma/metanorma-cli/actions/runs/4101141447/jobs/7073600661#step:7:33):in `generate'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	from /Users/runner/work/metanorma-cli/metanorma-cli/lib/metanorma/cli.rb:34:in `start'
	from /Users/runner/work/metanorma-cli/metanorma-cli/exe/metanorma:25:in `block in <top (required)>'
	from /Users/runner/work/metanorma-cli/metanorma-cli/exe/metanorma:43:in `<top (required)>'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/bin/metanorma:25:in `load'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/bin/metanorma:25:in `<top (required)>'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/3.2.0/bundler/cli.rb:491:in `exec'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/3.2.0/bundler/cli.rb:28:in `start'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.1/libexec/bundle:45:in `block in <top (required)>'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.1/libexec/bundle:[33](https://github.com/metanorma/metanorma-cli/actions/runs/4101141447/jobs/7073600661#step:7:35):in `<top (required)>'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x[64](https://github.com/metanorma/metanorma-cli/actions/runs/4101141447/jobs/7073600661#step:7:66)/bin/bundle:25:in `load'
	from /Users/runner/hostedtoolcache/Ruby/3.2.0/x64/bin/bundle:25:in `<main>'
```

**Comment by andrew2net** [comment]
fixed in the latest version
