### ISSUE TITLE
faraday-net_http_persistent dependency

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton#127]
https://github.com/metanorma/metanorma/issues/387

After an upgrade (`gem install metanorma-cli`) I had to manually do:

```
gem install faraday-net_http_persistent
```

for things to work, otherwise I would be getting a confusing error:

```
Fatal Error: undefined method `dependency' for Faraday::Adapter::NetHttpPersistent:Class
```

Could this be a missing dependency?

----

This has just happened in latest release. faraday-net_http_persistent is used by algolia, which you use. I have not had that issue.

**Comment by andrew2net** [comment]
@opoudjis you are right, the dependency chain is `mtenorma-cli -> relaton-cli -> relaton-bsi -> algolia -> faraday-net_http_persistent`, but it's resolved and installed correctly with `gem install metanorma-cli` command:
```
$ gem uninstall faraday-net_http_persistent

You have requested to uninstall the gem:
	faraday-net_http_persistent-2.1.0

algolia-2.3.4 depends on faraday-net_http_persistent (>= 0.15, < 3)
If you remove this gem, these dependencies will not be met.
Continue with Uninstall? [yN]  y
Successfully uninstalled faraday-net_http_persistent-2.1.0

$ gem uninstall metanorma-cli
Remove executables:
	metanorma, metanorma-manifest

in addition to the gem? [Yn]
Removing metanorma
Removing metanorma-manifest
Successfully uninstalled metanorma-cli-1.9.8

$ relaton git:(main) gem install metanorma-cli
Fetching faraday-net_http_persistent-2.1.0.gem
Fetching metanorma-cli-1.9.8.gem
Successfully installed faraday-net_http_persistent-2.1.0
Successfully installed metanorma-cli-1.9.8
2 gems installed
```
Can you get the whole error message with backtrace? It may help to find out what's going on.

**Comment by opoudjis** [comment]
@jerstlouis ? We are having trouble replicating

**Comment by jerstlouis** [comment]
```
 gem uninstall faraday-net_http_persistent

Select gem to uninstall:
 1. faraday-net_http_persistent-1.2.0
 2. faraday-net_http_persistent-2.1.0
 3. All versions
> 2
Successfully uninstalled faraday-net_http_persistent-2.1.0
Rainbow:[jerome]:~$ gem install metanorma-cli
Fetching asciidoctor-2.0.23.gem
Successfully installed asciidoctor-2.0.23
Successfully installed metanorma-cli-1.9.8
Parsing documentation for asciidoctor-2.0.23
Installing ri documentation for asciidoctor-2.0.23
Parsing documentation for metanorma-cli-1.9.8
Done installing documentation for asciidoctor, metanorma-cli after 1 seconds
2 gems installed

Rainbow:[jerome]:~/specs/ogcapi-discrete-global-grid-systems/core$ metanorma 21-038.adoc 
Fatal Error: undefined method `dependency' for Faraday::Adapter::NetHttpPersistent:Class
/home/jerome/.gem/ruby/3.0.0/gems/faraday-net_http_persistent-1.2.0/lib/faraday/adapter/net_http_persistent.rb:7:in `<class:NetHttpPersistent>': undefined method `dependency' for Faraday::Adapter::NetHttpPersistent:Class (NoMethodError)
	from /home/jerome/.gem/ruby/3.0.0/gems/faraday-net_http_persistent-1.2.0/lib/faraday/adapter/net_http_persistent.rb:6:in `<class:Adapter>'
	from /home/jerome/.gem/ruby/3.0.0/gems/faraday-net_http_persistent-1.2.0/lib/faraday/adapter/net_http_persistent.rb:4:in `<module:Faraday>'
	from /home/jerome/.gem/ruby/3.0.0/gems/faraday-net_http_persistent-1.2.0/lib/faraday/adapter/net_http_persistent.rb:3:in `<top (required)>'
	from /home/jerome/.gem/ruby/3.0.0/gems/faraday-net_http_persistent-1.2.0/lib/faraday/net_http_persistent.rb:3:in `require_relative'
	from /home/jerome/.gem/ruby/3.0.0/gems/faraday-net_http_persistent-1.2.0/lib/faraday/net_http_persistent.rb:3:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/jerome/.gem/ruby/3.0.0/gems/algolia-2.3.2/lib/algolia/transport/transport.rb:3:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/jerome/.gem/ruby/3.0.0/gems/algolia-2.3.2/lib/algolia.rb:31:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/jerome/.gem/ruby/3.0.0/gems/relaton-iso-1.18.2/lib/relaton_iso/hit_collection.rb:3:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/jerome/.gem/ruby/3.0.0/gems/relaton-iso-1.18.2/lib/relaton_iso/iso_bibliography.rb:5:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/jerome/.gem/ruby/3.0.0/gems/relaton-iso-1.18.2/lib/relaton_iso.rb:14:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/jerome/.gem/ruby/3.0.0/gems/relaton-1.18.1/lib/relaton/registry.rb:29:in `block in register_gems'
	from /home/jerome/.gem/ruby/3.0.0/gems/relaton-1.18.1/lib/relaton/registry.rb:28:in `each'
	from /home/jerome/.gem/ruby/3.0.0/gems/relaton-1.18.1/lib/relaton/registry.rb:28:in `register_gems'
	from /home/jerome/.gem/ruby/3.0.0/gems/relaton-1.18.1/lib/relaton/registry.rb:22:in `initialize'
	from /usr/lib/ruby/3.0.0/singleton.rb:127:in `new'
	from /usr/lib/ruby/3.0.0/singleton.rb:127:in `block in instance'
	from /usr/lib/ruby/3.0.0/singleton.rb:125:in `synchronize'
	from /usr/lib/ruby/3.0.0/singleton.rb:125:in `instance'
	from /home/jerome/.gem/ruby/3.0.0/gems/relaton-1.18.1/lib/relaton/db.rb:6:in `initialize'
	from /home/jerome/.gem/ruby/3.0.0/gems/relaton-1.18.1/lib/relaton/db.rb:552:in `new'
	from /home/jerome/.gem/ruby/3.0.0/gems/relaton-1.18.1/lib/relaton/db.rb:552:in `init_bib_caches'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-standoc-2.8.9/lib/metanorma/standoc/ref_queue.rb:220:in `init_bib_caches'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-standoc-2.8.9/lib/metanorma/standoc/init.rb:103:in `init_biblio'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-standoc-2.8.9/lib/metanorma/standoc/init.rb:12:in `init'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-standoc-2.8.9/lib/metanorma/standoc/base.rb:42:in `document1'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-standoc-2.8.9/lib/metanorma/standoc/base.rb:32:in `document'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-standoc-2.8.9/lib/metanorma/standoc/utils.rb:13:in `convert'
	from /home/jerome/.gem/ruby/3.0.0/gems/asciidoctor-2.0.23/lib/asciidoctor/document.rb:956:in `convert'
	from /home/jerome/.gem/ruby/3.0.0/gems/asciidoctor-2.0.23/lib/asciidoctor/convert.rb:120:in `convert'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-1.7.7/lib/metanorma/input/asciidoc.rb:17:in `process'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-1.7.7/lib/metanorma/processor.rb:21:in `input_to_isodoc'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-1.7.7/lib/metanorma/compile.rb:72:in `process_input_adoc'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-1.7.7/lib/metanorma/compile.rb:54:in `process_input'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-1.7.7/lib/metanorma/compile.rb:32:in `compile'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-cli-1.9.8/lib/metanorma/cli/compiler.rb:45:in `compile_file'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-cli-1.9.8/lib/metanorma/cli/compiler.rb:30:in `compile'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-cli-1.9.8/lib/metanorma/cli/compiler.rb:35:in `compile'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-cli-1.9.8/lib/metanorma/cli/command.rb:244:in `compile_document'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-cli-1.9.8/lib/metanorma/cli/command.rb:48:in `block in compile'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-cli-1.9.8/lib/metanorma/cli/command.rb:48:in `each'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-cli-1.9.8/lib/metanorma/cli/command.rb:48:in `compile'
	from /home/jerome/.gem/ruby/3.0.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
	from /home/jerome/.gem/ruby/3.0.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
	from /home/jerome/.gem/ruby/3.0.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/jerome/.gem/ruby/3.0.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
	from /home/jerome/.gem/ruby/3.0.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-cli-1.9.8/lib/metanorma/cli.rb:34:in `start'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-cli-1.9.8/exe/metanorma:25:in `block in <top (required)>'
	from /home/jerome/.gem/ruby/3.0.0/gems/metanorma-cli-1.9.8/exe/metanorma:43:in `<top (required)>'
	from /home/jerome/.gem/ruby/3.0.0/bin/metanorma:25:in `load'
	from /home/jerome/.gem/ruby/3.0.0/bin/metanorma:25:in `<main>'
Rainbow:[jerome]:~/specs/ogcapi-discrete-global-grid-systems/core$ 

```

**Comment by jerstlouis** [comment]
@andrew2net @opoudjis It seems like the dependency matching is happy with version 1.2 being installed, but it requires a later version.

**Comment by andrew2net** [comment]
@jerstlouis you are right. We use an `algolia` gem. The gem depends on `faraday-net_http_persistent` and allows versions `>= 0.15, < 3`. But it fails with the version 1.2. So I added the dependency to our gemspec with `~> 2.0` version restriction.
Please update relaton-iso to v1.18.3 and relaton-bsi to v1.18.1

**Comment by ronaldtse** [comment]
Thank you @jerstlouis and @andrew2net !
