### ISSUE TITLE
wrapped reference triggering infinite loop

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton#64]
If I attempt to fetch a wrapped citation like

````
 * [[[ref4,CN(GB 12663-2019)]]], _Standard GB 123_
````

I end up with an infinite loop in db_cache.rb:

````
     # /Users/nickn/.rvm/gems/ruby-2.5.1/gems/relaton-0.5.9/lib/relaton/db_cache.rb:37:in `[]'
     # /Users/nickn/.rvm/gems/ruby-2.5.1/gems/relaton-0.5.9/lib/relaton/db_cache.rb:37:in `[]'
     # /Users/nickn/.rvm/gems/ruby-2.5.1/gems/relaton-0.5.9/lib/relaton/db_cache.rb:37:in `[]'
     # /Users/nickn/.rvm/gems/ruby-2.5.1/gems/relaton-0.5.9/lib/relaton/db_cache.rb:37:in `[]'
     # /Users/nickn/.rvm/gems/ruby-2.5.1/gems/relaton-0.5.9/lib/relaton/db_cache.rb:37:in `[]'
     # /Users/nickn/.rvm/gems/ruby-2.5.1/gems/relaton-0.5.9/lib/relaton/db.rb:168:in `check_bibliocache'
     # /Users/nickn/.rvm/gems/ruby-2.5.1/gems/relaton-0.5.9/lib/relaton/db.rb:33:in `fetch'
     # /Users/nickn/.rvm/gems/ruby-2.5.1/gems/metanorma-standoc-1.3.6/lib/asciidoctor/standoc/ref.rb:110:in `fetch_ref'
     # /Users/nickn/.rvm/gems/ruby-2.5.1/gems/metanorma-standoc-1.3.6/lib/asciidoctor/standoc/ref.rb:135:in `refitem'
     # /Users/nickn/.rvm/gems/ruby-2.5.1/gems/metanorma-standoc-1.3.6/lib/asciidoctor/standoc/ref.rb:188:in `reference1'
     # /Users/nickn/.rvm/gems/ruby-2.5.1/gems/metanorma-standoc-1.3.6/lib/asciidoctor/standoc/ref.rb:199:in `block (2 levels) in reference'
````

This is calling relaton `fetch` in lib/relaton/db.rb as `fetch("CN(GB 12663-2019)"), nil, {:title=>"<em>Standard GB 123</em>"})`. I am presuming the caching is having trouble with the brackets.

**Comment by andrew2net** [comment]
@opoudjis I tried it with the last `relaton` 0.5.10 version:
```
[4] pry(main)> item = db.fetch("CN(GB 12663-2019)", nil, {:title=>"<em>Standard GB 123</em>"})
fetching GB 12663-2019...
=> <RelatonGb::GbBibliographicItem:0x007ff9baa323a0>
```
By the way there is a typo in your example. It has an exra right bracket after the reference.
Could you try to update `relaton`?

**Comment by ronaldtse** [comment]
I just got this error with this:

```
fetching ISO/IEC 6523...
bundler: failed to load command: metanorma (/Users/me/.rbenv/versions/2.6.5/bin/metanorma)
SystemStackError: stack level too deep
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-0.5.10/lib/relaton/db_cache.rb:133:in `match'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-0.5.10/lib/relaton/db_cache.rb:133:in `filename'
```
