### ISSUE TITLE
Infinite loop crash: "all parts" citations e.g. ISO 9735, 13399 crashes at infinite loop all the time

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton#66]
The following ISO document generates an infinite loop within relaton:

````
= X 
A 
:local-cache-only:

[bibliography]
== Bibliography

* [[[ISO_9735,ISO 9735 (all parts)]]], _Electronic data interchange for administration commerce and transport (EDIFACT) -- Application level syntax rules_.
````

~~Without `:local-cache-only:` directive, the code generates fine.~~ (Ron: This is not true)

`metanorma -t iso test.adoc` to reproduce, with test.adoc containing the snippet above.

**Comment by ronaldtse** [comment]
Same issue for me.

ISO 13399 => 

```
fetching ISO 12620...
fetching ISO 13399...
bundler: failed to load command: metanorma (/Users/ronaldtse/.rbenv/versions/2.6.5/bin/metanorma)
SystemStackError: stack level too deep
  /Users/ronaldtse/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-0.5.13/lib/relaton/db_cache.rb:133:in `match'
  /Users/ronaldtse/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-0.5.13/lib/relaton/db_cache.rb:133:in `filename'
  /Users/ronaldtse/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-0.5.13/lib/relaton/db_cache.rb:112:in `get'
  /Users/ronaldtse/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-0.5.13/lib/relaton/db_cache.rb:35:in `[]'
  /Users/ronaldtse/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-0.5.13/lib/relaton/db_cache.rb:37:in `[]'
  /Users/ronaldtse/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-0.5.13/lib/relaton/db_cache.rb:37:in `[]'
  /Users/ronaldtse/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-0.5.13/lib/relaton/db_cache.rb:37:in `[]'
  /Users/ronaldtse/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-0.5.13/lib/relaton/db_cache.rb:37:in `[]'
```

Content of `relaton/iso_13399_all_parts.xml`:
```
redirection ISO(ISO 13399 (all parts))
```

**Comment by ronaldtse** [comment]
In fact, there is nothing to do with local cache. Without local cache, the global cache can also get polluted with the same "infinite loop file" and causes Relaton to crash. This is a CRITICAL bug.
