### ISSUE TITLE
fetch_async is broken

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton#95]
Following the example provided in the README, I tried using `fetch_async`.

`x.rb`:
```ruby
#!/usr/bin/env ruby

require "relaton"

$stdout.sync

# prepare queue for results
results = Queue.new

# references ot fetch
refs = ["ISO 19011", "ISO 19115", "ISO 9001", "ISO 14001"]
expected_fetches = refs.length

db = Relaton::Db.new(nil, nil)

refs.each do |ref|
  db.fetch_async(ref) do |doc_id, ref|
    # beware that `ref` must be passed in as a block argument
    # otherwise it can refer to another redefined `ref` in this
    # loop

    puts "fetching #{doc_id}..."
    results << [ref, doc_id]
    puts "finish fetching #{doc_id}, #{ref}"
  end
end

while results.size < expected_fetches do
  puts "sleeping"
  sleep 1
end

while popped = results.pop do
  ref, doc_id = popped
  puts "popped!"
  puts ref, doc_id
end
```

```sh
$ ./x.sh
[relaton] Info: detecting backends:
sleeping
[relaton-iso] ("ISO 9001") fetching...
[relaton-iso] ("ISO 19115") fetching...
[relaton-iso] ("ISO 19011") fetching...
sleeping
sleeping
sleeping
sleeping
sleeping
[relaton-iso] ("ISO 19115") found ISO 19115:2003
fetching #<RelatonIsoBib::IsoBibliographicItem:0x00007ff2f32a9908>...
finish fetching #<RelatonIsoBib::IsoBibliographicItem:0x00007ff2f32a9908>, 
[relaton-iso] ("ISO 14001") fetching...
[relaton-iso] ("ISO 19011") found ISO 19011:2018
fetching #<RelatonIsoBib::IsoBibliographicItem:0x00007ff2d355ed80>...
finish fetching #<RelatonIsoBib::IsoBibliographicItem:0x00007ff2d355ed80>, 
[relaton-iso] ("ISO 9001") found ISO 9001:2015
fetching #<RelatonIsoBib::IsoBibliographicItem:0x00007ff2f6bbb430>...
finish fetching #<RelatonIsoBib::IsoBibliographicItem:0x00007ff2f6bbb430>, 
sleeping
sleeping
sleeping
sleeping
[relaton-iso] ("ISO 14001") found ISO 14001:2015
fetching #<RelatonIsoBib::IsoBibliographicItem:0x00007ff2d332f5a0>...
finish fetching #<RelatonIsoBib::IsoBibliographicItem:0x00007ff2d332f5a0>, 
popped!

#<RelatonIsoBib::IsoBibliographicItem:0x00007ff2f32a9908>
popped!

#<RelatonIsoBib::IsoBibliographicItem:0x00007ff2d355ed80>
popped!

#<RelatonIsoBib::IsoBibliographicItem:0x00007ff2f6bbb430>
popped!

#<RelatonIsoBib::IsoBibliographicItem:0x00007ff2d332f5a0>
./x.rb:29:in `pop': No live threads left. Deadlock? (fatal)
5 threads, 5 sleeps current:0x00007ff2f2e060d0 main thread:0x00007ff2f2e060d0
* #<Thread:0x00007ff2f387bc00 sleep_forever>
   rb_thread_t:0x00007ff2f2e060d0 native:0x000000010ad19e00 int:0
   
* #<Thread:0x00007ff2f3341d98 /Users/me/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/relaton-1.9.1/lib/relaton/workers_pool.rb:10 sleep_forever>
   rb_thread_t:0x00007ff27393f8d0 native:0x000070000a782000 int:0
   
* #<Thread:0x00007ff2f3341bb8 /Users/me/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/relaton-1.9.1/lib/relaton/workers_pool.rb:10 sleep_forever>
   rb_thread_t:0x00007ff273941470 native:0x000070000a985000 int:0
   
* #<Thread:0x00007ff2f3341ac8 /Users/me/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/relaton-1.9.1/lib/relaton/workers_pool.rb:10 sleep_forever>
   rb_thread_t:0x00007ff273941960 native:0x000070000ab88000 int:0
   
* #<Thread:0x00007ff2f33418c0 /Users/me/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/relaton-1.9.1/lib/relaton/db.rb:109 sleep_forever>
   rb_thread_t:0x00007ff273941ed0 native:0x000070000ad8b000 int:0
   
	from ./x.rb:29:in `<main>'
```

Not supposed to fail on exit.

The concurrent-ruby library provides basic things like ThreadPool, and there is no reason to re-implement things like that inside Relaton. Please help reimplement this.

**Comment by andrew2net** [comment]
@ronaldtse in this case x.rb crashes because of `while popped = results.pop do`. Queue's instance doesn't return false or nil when it's empty. The concurent-ruby gem won't fix it.
In the example, the size of the list of references is used. This script works correctly:
```
#!/usr/bin/env ruby

require "relaton"

$stdout.sync

# prepare queue for results
results = Queue.new

# references ot fetch
refs = ["ISO 19011", "ISO 19115", "ISO 9001", "ISO 14001"]
expected_fetches = refs.length

db = Relaton::Db.new(nil, nil)

refs.each do |ref|
  db.fetch_async(ref, ref: ref) do |doc_id, args|
    # beware that `ref` must be passed in as a block argument
    # otherwise it can refer to another redefined `ref` in this
    # loop

    puts "fetching #{doc_id}..."
    results << [args[:ref], doc_id]
    puts "finish fetching #{doc_id}, #{args[:ref]}"
  end
end

expected_fetches.times do
  popped = results.pop
  ref, doc_id = popped
  puts "popped!"
  puts ref, doc_id
end
```
Please pay attention, I've changed today the way how additional data, like a reference, is passed to a worker.
The relaton creates a thread pool for each flavor gem. This allows implementing flavor gems-related restrictions like max threads number, max requests/sec, etc. It will be tricky to implement with the concurrent-ruby library. On the other hand, relaton's workers don't use shared variables. Relaton just reads data and puts it in a Queue instance, which is thread-safe by its nature.

**Comment by ronaldtse** [comment]
Wow, did not know Thread::Queue waits to return. That's certainly easier for the programmer. 

> This allows implementing flavor gems-related restrictions like max threads number, max requests/sec, etc. It will be tricky to implement with the concurrent-ruby library.

Why can't this be implemented on top of concurrent-ruby's ThreadPool?

**Comment by andrew2net** [comment]
@ronaldtse with custom thread pool we can control an inner queue. It needs in case a site from which we fetching documents restricts the number of requests per second or minute. It isn't implemented yet but we will likely need it later for some data sources.

**Comment by ronaldtse** [comment]
> It needs in case a site from which we fetching documents restricts the number of requests per second or minute.

You can technically implement this using another Queue that stores a number of "tokens" (a "token queue"), where a thread pool thread needs to first fetch a token to process a remote request, and re-inserts the token back to the Queue once done.
