### ISSUE TITLE
File /root/.relaton/nist/pubs-export.zip has zero size. Did you mean to pass the create flag? (Zip::Error)

### ISSUE THREAD

**Issue by CAMOBAP** [relaton/relaton#99]
### Problem

During compilation of https://github.com/metanorma/mn-samples-nist (private repo) sometimes `Zip::Error` happens

```
Run docker run -v $(pwd):/metanorma/ metanorma-nist/metanorma:latest metanorma site generate --agree-to-terms .
[info]: Compiling /metanorma/sources/800-53r4/document.adoc ...
[relaton] Info: detecting backends:
[relaton-iso] ("ISO/IEC 27001") fetching...
[relaton-iso] ("ISO/IEC 15408-1") fetching...
[relaton-nist] ("NIST FIPS 186-3") fetching...
[relaton-nist] ("NIST FIPS 188") fetching...
[relaton-nist] ("NIST FIPS 190") fetching...
[relaton-nist] ("NIST FIPS 199") fetching...
[relaton-nist] ("NIST FIPS 197") fetching...
[relaton-nist] ("NIST FIPS 200") fetching...
[relaton-nist] ("NIST FIPS 198-1") fetching...
[relaton-nist] ("NIST FIPS 201-1") fetching...
[relaton-nist] ("NIST FIPS 180-4") fetching...
[relaton-iso] ("ISO/IEC 15408-2") fetching...
[relaton-nist] ("NIST FIPS 140-2") fetching...
[relaton-nist] ("NIST FIPS 201-1") found FIPS 201-1
#<Thread:0x000055910fec8880 /usr/local/bundle/gems/relaton-1.10.2/lib/relaton/workers_pool.rb:10 run> terminated with exception (report_on_exception is true):
/usr/local/bundle/gems/rubyzip-2.3.2/lib/zip/file.rb:103:in `initialize': File /root/.relaton/nist/pubs-export.zip has zero size. Did you mean to pass the create flag? (Zip::Error)
	from /usr/local/bundle/gems/rubyzip-2.3.2/lib/zip/file.rb:121:in `new'
	from /usr/local/bundle/gems/rubyzip-2.3.2/lib/zip/file.rb:121:in `open'
	from /usr/local/bundle/gems/relaton-nist-1.10.1/lib/relaton_nist/hit_collection.rb:165:in `unzip'
	from /usr/local/bundle/gems/relaton-nist-1.10.1/lib/relaton_nist/hit_collection.rb:143:in `data'
	from /usr/local/bundle/gems/relaton-nist-1.10.1/lib/relaton_nist/hit_collection.rb:114:in `select_data'
	from /usr/local/bundle/gems/relaton-nist-1.10.1/lib/relaton_nist/hit_collection.rb:99:in `from_json'
	from /usr/local/bundle/gems/relaton-nist-1.10.1/lib/relaton_nist/hit_collection.rb:23:in `search'
	from /usr/local/bundle/gems/relaton-nist-1.10.1/lib/relaton_nist/hit_collection.rb:19:in `search'
	from /usr/local/bundle/gems/relaton-nist-1.10.1/lib/relaton_nist/nist_bibliography.rb:17:in `search'
	from /usr/local/bundle/gems/relaton-nist-1.10.1/lib/relaton_nist/nist_bibliography.rb:177:in `nistbib_search_filter'
	from /usr/local/bundle/gems/relaton-nist-1.10.1/lib/relaton_nist/nist_bibliography.rb:64:in `nistbib_get1'
	from /usr/local/bundle/gems/relaton-nist-1.10.1/lib/relaton_nist/nist_bibliography.rb:[58](https://github.com/metanorma/metanorma-docker-private/runs/5491422009?check_suite_focus=true#step:12:58):in `get'
	from /usr/local/bundle/gems/relaton-nist-1.10.1/lib/relaton_nist/processor.rb:18:in `get'
	from /usr/local/bundle/gems/relaton-1.10.2/lib/relaton/db.rb:[4](https://github.com/metanorma/metanorma-docker-private/runs/5491422009?check_suite_focus=true#step:12:4)32:in `net_retry'
	from /usr/local/bundle/gems/relaton-1.10.2/lib/relaton/db.rb:417:in `new_bib_entry'
	from /usr/local/bundle/gems/relaton-1.10.2/lib/relaton/db.rb:397:in `check_bibliocache'
	from /usr/local/bundle/gems/relaton-1.10.2/lib/relaton/db.rb:74:in `fetch'
	from /usr/local/bundle/gems/relaton-1.10.2/lib/relaton/db.rb:110:in `block in fetch_async'
	from /usr/local/bundle/gems/relaton-1.10.2/lib/relaton/workers_pool.rb:11:in `block (2 levels) in initialize'
[relaton-nist] ("NIST FIPS 190") found FIPS 190
[relaton-nist] ("NIST FIPS 186-3") found FIPS 186-3
[relaton-nist] ("NIST FIPS 140-2") found FIPS 140-2
[relaton-iso] WARNING: no match found online for ISO/IEC 27001:200[5](https://github.com/metanorma/metanorma-docker-private/runs/5491422009?check_suite_focus=true#step:12:5). The code must be exactly like it is on the standards website.
[relaton-iso] (There was no match for 2005, though there were matches found for 2013, .)
[relaton-iso] If you wanted to cite all document parts for the reference, use "ISO/IEC 2[7](https://github.com/metanorma/metanorma-docker-private/runs/5491422009?check_suite_focus=true#step:12:7)001 (all parts)".
If the document is not a standard, use its document type abbreviation (TS, TR, PAS, Guide).
[relaton-nist] ("NIST FIPS 1[8](https://github.com/metanorma/metanorma-docker-private/runs/5491422009?check_suite_focus=true#step:12:8)8") found FIPS 188
[relaton-nist] ("NIST FIPS 1[9](https://github.com/metanorma/metanorma-docker-private/runs/5491422009?check_suite_focus=true#step:12:9)9") found FIPS 199
[relaton-nist] ("NIST FIPS 197") found FIPS 197
[relaton-nist] ("NIST FIPS 200") found FIPS 200
[relaton-nist] ("NIST FIPS 198-1") found FIPS 198-1
[relaton-iso] ("ISO/IEC [15](https://github.com/metanorma/metanorma-docker-private/runs/5491422009?check_suite_focus=true#step:12:15)408-3") fetching...
[relaton-iso] ("ISO/IEC 15408-1") found ISO/IEC 15408-1:[20](https://github.com/metanorma/metanorma-docker-private/runs/5491422009?check_suite_focus=true#step:12:20)09
[relaton-iso] ("ISO/IEC 15[40](https://github.com/metanorma/metanorma-docker-private/runs/5491422009?check_suite_focus=true#step:12:40)8-2") found ISO/IEC 1[54](https://github.com/metanorma/metanorma-docker-private/runs/5491422009?check_suite_focus=true#step:12:54)08-2:2008
[relaton-iso] ("ISO/IEC 15408-3") found ISO/IEC 15408-3:2008
```

### Workaround 

`ENV['RELATON_FETCH_PARALLEL'] = '1' - works

**Comment by andrew2net** [comment]
added zero size checking in version 1.11.1
